# Generated by Django 5.0.7 on 2024-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='javascript', max_length=255),
        ),
    ]
